@startuml

title __CONTROLLERS's Class Diagram__\n

    class fr.projava.triangle.Controllers.AccountController {
        {static} - user : User
        {static} + changePseudo()
        {static} + closeConnection()
        {static} + connectToAccount()
        {static} + getUser()
        {static} + newAccount()
        {static} - getMAC()
    }
  

    class fr.projava.triangle.Controllers.ConversationController {
        {static} + loadHistory()
        {static} + receiveMessage()
        {static} + sendMessage()
    }


    class fr.projava.triangle.Controllers.DatabaseController {
        {static} ~ connection : Connection
        + DatabaseController()
        {static} + addMessage()
        {static} + addUser()
        {static} + existingAccount()
        {static} + existingMAC()
        {static} + getUserID()
        {static} + loadHistory()
        {static} + updateAccount()
    }


    class fr.projava.triangle.Controllers.NetworkController {
        {static} - serverSocket : ServerSocket
        {static} - socket : DatagramSocket
        {static} + broadcastUDP()
        {static} + closeListenTCP()
            {static} + closeListenUDP()
        {static} + findBroadcastAddress()
        {static} + listenTCP()
        {static} + listenUDP()
        {static} + openServerSocket()
        {static} + openSocketUDP()
        {static} + sendTCP()
        {static} + sendUDP()
        {static} - processText()
    }

  

    class fr.projava.triangle.Controllers.ThreadController {
        {static} ~ listenerTCP : MThread
        {static} ~ listenerUDP : MThread
        + ThreadController()
        {static} + broadcastConnection()
        {static} + broadcastDisconnection()
        {static} + launchListeningThreadTCP()
        {static} + launchListeningThreadUDP()
        {static} + sendTCP()
        {static} + stopListeningThreadTCP()
        {static} + stopListeningThreadUDP()
        {static} + validPseudo()
    }

  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
